### ISSUE TITLE
Slack invitation was invoked

### ISSUE THREAD

**Issue by suguanYang** [collabnix/gopherlabs#5]

**Comment by sangam14** [comment]
https://join.slack.com/t/collabnix/shared_invite/enQtODgyMjk0MzU5ODQyLTM1MGI0M2EzMGM3MTNlYTI0OGFiNjY2NzI1OTY2N2E1Yjk1N2NjZDMzZDk1NmYyMTJiYTA1ODMyNDNlNzc3MjU

**Comment by sangam14** [comment]
sugan yang join with above links

**Comment by vikas027** [comment]
Hey @sangam14 ,

The URL is not working again. Can you please have a look? TIA

**Comment by sangam14** [comment]
In the live session get back to you soon

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by sangam14** [comment]
Get Outlook for Android<https://aka.ms/ghei36>
________________________________
